## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/
image:
  repo: "registry.au-syd.bluemix.net/zmon/zmon-listener"
  tag: "1.11.1"
  pullPolicy: IfNotPresent

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 1

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Configure the service for this telegraf instance. If you are running
## Any of the service plugins you will need this enabled
## Service Plugins: http_listener, statsd, tcp_listener, udp_listener
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  enabled: true
  type: ClusterIP

## Exposed telegraf configuration
## For full list of possible values see `/docs/all-config-values.yaml` and `/docs/all-config-values.toml`
## ref: https://docs.influxdata.com/telegraf/v1.8/administration/configuration/

config:
  agent:
    interval: "10s"
    round_interval: true
    metric_batch_size: 1000
    metric_buffer_limit: 10000
    collection_jitter: "0s"
    flush_interval: "10s"
    flush_jitter: "0s"
    precision: ""
    debug: false
    quiet: false
    logfile: ""
    hostname: "telegraf-polling-service"
    omit_hostname: false
  inputs:
   ## listener input
   - influxdb_listener:
       service_address: ":18080"
       # todo insert tenantID
       basic_username: "{ tenantID }"
       # todo insert tenant password
       basic_password: ""
       read_timeout: "10s"
       write_timeout: "10s"
  aggregators:
    - final:
        period: "1m"
        drop_original: true
        series_timeout: "5s"

  outputs:
   ## listener output
   - kafka:
       brokers:
         - "10.178.51.133:9093"
         - "10.178.51.136:9093"
         - "10.178.51.164:9093"
       # todo insert tenantID
       topic: "telegraf__{ tenantID }"
       compression_codec: 0
       required_acks: -1
       max_retry: 3
       data_format: "influx"
